name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: portfolio


jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
         docker build . --tag ghcr.io/westfox-5/portfolio:latest
         docker push ghcr.io/westfox-5/portfolio:latest
